// Entry point. The Worker's code lives in the @trustdata/ai-bot-collector npm
// package, pinned in package.json — this file only re-exports its handler, and
// never needs to change. To upgrade the Worker, merge the update pull request
// (see README); do not edit this file or wrangler.jsonc.
export { default } from "@trustdata/ai-bot-collector";
